#ifndef F44REDCOIN_CHAINPARAMSSEEDS_H
#define F44REDCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the f44redcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x6c,0x3d,0x9d,0x14}, 8833}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // F44REDCOIN_CHAINPARAMSSEEDS_H
